{%- macro form_ids_type(primary_attribute_value) -%}

CASE
    WHEN {{ primary_attribute_value }} LIKE 'FORM 3162%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3245%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1754%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1476%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3226%'
    THEN 'Inbound - High'
    WHEN {{ primary_attribute_value }} LIKE 'FORM 1102%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1077%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1546%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1547%'
        OR {{ primary_attribute_value }} LIKE 'FORM 2425%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3119%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3686%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3687%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1364%'
        OR {{ primary_attribute_value }} LIKE 'FORM 3814%'
        OR {{ primary_attribute_value }} LIKE 'FORM 1073%'
    THEN 'Subscription'
    WHEN {{ primary_attribute_value }} LIKE '%FORM 1318%'
        OR {{ primary_attribute_value }} LIKE '%FORM 2150%'
        OR {{ primary_attribute_value }} LIKE '%FORM 3438%'
        OR {{ primary_attribute_value }} LIKE '%FORM 3648%'
        OR {{ primary_attribute_value }} LIKE '%FORM 3240%'
    THEN 'Trial'
    WHEN {{ primary_attribute_value }} NOT LIKE '%FORM 1318%'
        AND {{ primary_attribute_value }} NOT LIKE '%FORM 2150%'
        AND {{ primary_attribute_value }} NOT LIKE '%FORM 3438%'
        AND {{ primary_attribute_value }} NOT LIKE '%FORM 3648%'
        AND {{ primary_attribute_value }} NOT LIKE '%FORM 3240%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1102%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1077%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1546%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1547%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 2425%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3119%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3686%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3687%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1364%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3814%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1073%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3162%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3245%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1754%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 1476%'
        AND {{ primary_attribute_value }} NOT LIKE 'FORM 3226%'
    THEN 'General'
END AS form_ids_type

{%- endmacro -%}
