{{ config(
    materialized="table"
) }}

{{ simple_cte([
    ('mart_product_usage_paid_user_metrics_monthly','mart_product_usage_paid_user_metrics_monthly'),
    ('mart_product_usage_free_user_metrics_monthly', 'mart_product_usage_free_user_metrics_monthly')
]) }}

, final AS (

    SELECT
        'Paid' AS product_user_type,
        dim_crm_account_id,
        dim_namespace_id,
        analytics_value_stream_28_days_event,
        api_fuzzing_scans_28_days_event,
        api_fuzzing_scans_all_time_event,
        billable_user_count,
        ci_builds_all_time_event,
        code_review_user_approve_mr_28_days_user,
        compliance_dashboard_view_28_days_user,
        container_scanning_scans_28_days_event,
        container_scanning_scans_all_time_event,
        coverage_fuzzing_scans_28_days_event,
        coverage_fuzzing_scans_all_time_event,
        custom_compliance_frameworks_28_days_event,
        dast_scans_28_days_event,
        dast_scans_all_time_event,
        delivery_type,
        dependency_scanning_scans_28_days_event,
        dependency_scanning_scans_all_time_event,
        deployment_type,
        deployments_28_days_user,
        duo_enterprise_billable_user_count,
        duo_pro_billable_user_count,
        environments_all_time_event,
        epics_all_time_event,
        external_status_checks_all_time_event,
        failed_deployments_28_days_event,
        feature_flags_all_time_event,
        group_saml_enabled,
        groups_all_time_event,
        hostname,
        issues_all_time_event,
        jira_issue_imports_all_time_event,
        merge_requests_28_days_user,
        merge_requests_all_time_event,
        merge_requests_approval_rules_28_days_event,
        merge_requests_created_28_days_event,
        merge_requests_created_28_days_user,
        merge_requests_security_policy_28_days_user,
        merge_requests_with_required_code_owners_28_days_user,
        ping_created_at,
        pipeline_schedules_all_time_event,
        projects_github_active_all_time_event,
        projects_imported_all_time_event,
        projects_jira_active_28_days_user,
        projects_jira_active_all_time_event,
        projects_security_policy_28_days_event,
        projects_with_packages_all_time_event,
        sast_scans_28_days_event,
        sast_scans_all_time_event,
        secret_detection_scans_28_days_event,
        secret_detection_scans_all_time_event,
        source_code_pushes_all_time_event,
        successful_deployments_28_days_event
    FROM mart_product_usage_paid_user_metrics_monthly
    WHERE ping_created_at >= '2024-02-01'
    UNION ALL
    SELECT
        'Free' AS product_user_type,
        dim_crm_account_id,
        dim_namespace_id,
        analytics_value_stream_28_days_event,
        api_fuzzing_scans_28_days_event,
        api_fuzzing_scans_all_time_event,
        NULL AS billable_user_count,
        ci_builds_all_time_event,
        code_review_user_approve_mr_28_days_user,
        compliance_dashboard_view_28_days_user,
        container_scanning_scans_28_days_event,
        container_scanning_scans_all_time_event,
        coverage_fuzzing_scans_28_days_event,
        coverage_fuzzing_scans_all_time_event,
        custom_compliance_frameworks_28_days_event,
        dast_scans_28_days_event,
        dast_scans_all_time_event,
        delivery_type,
        dependency_scanning_scans_28_days_event,
        dependency_scanning_scans_all_time_event,
        deployment_type,
        deployments_28_days_user,
        NULL AS duo_enterprise_billable_user_count,
        NULL AS duo_pro_billable_user_count,
        environments_all_time_event,
        epics_all_time_event,
        external_status_checks_all_time_event,
        failed_deployments_28_days_event,
        feature_flags_all_time_event,
        group_saml_enabled,
        NULL AS groups_all_time_event,
        hostname,
        issues_all_time_event,
        jira_issue_imports_all_time_event,
        merge_requests_28_days_user,
        merge_requests_all_time_event,
        merge_requests_approval_rules_28_days_event,
        merge_requests_created_28_days_event,
        merge_requests_created_28_days_user,
        merge_requests_security_policy_28_days_user,
        merge_requests_with_required_code_owners_28_days_user,
        ping_date,
        NULL AS pipeline_schedules_all_time_event,
        projects_github_active_all_time_event,
        projects_imported_all_time_event,
        projects_jira_active_28_days_user,
        projects_jira_active_all_time_event,
        projects_security_policy_28_days_event,
        projects_with_packages_all_time_event,
        sast_scans_28_days_event,
        sast_scans_all_time_event,
        secret_detection_scans_28_days_event,
        secret_detection_scans_all_time_event,
        source_code_pushes_all_time_event,
        successful_deployments_28_days_event
    FROM mart_product_usage_free_user_metrics_monthly
    WHERE ping_date >= '2024-02-01'

)

SELECT *
FROM final