# Metastore requests

@ib_server=http://localhost:3000

###
# List all volumes
# @name listVolumes

GET {{ib_server}}/v1/metastore/volumes

###
# Create a volume
# @name createVolume

POST {{ib_server}}/v1/metastore/volumes
Content-Type: application/json

{
    "ident": "my-volume",
    "type": "memory"
}

###
# Get a volume
# @name getVolume

GET {{ib_server}}/v1/metastore/volumes/my-volume

###
# Delete a volume
# @name deleteVolume

DELETE {{ib_server}}/v1/metastore/volumes/my-volume

###
# List all databases
# @name listDatabases

GET {{ib_server}}/v1/metastore/databases

###
# Create a database
# @name createDatabase
POST {{ib_server}}/v1/metastore/databases
Content-Type: application/json

{
    "ident": "my-database",
    "volume": "my-volume"
}

###
# Get a database
# @name getDatabase

GET {{ib_server}}/v1/metastore/databases/my-database

###
# Delete a database
# @name deleteDatabase

DELETE {{ib_server}}/v1/metastore/databases/my-database

###
# List all schemas
# @name listSchemas

GET {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas

###
# Create a schema
# @name createSchema

POST {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas
Content-Type: application/json

{
    "ident": {
        "schema": "my-schema",
        "database": "{{listDatabases.response.body.$[0].ident}}"
    }
}

###
# Get a schema
# @name getSchema

GET {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}

###
# Delete a schema
# @name deleteSchema

DELETE {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}

###
# List all tables
# @name listTables

GET {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}/tables

###
# Create a table
# @name createTable
POST {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}/tables
Content-Type: application/json

{
    "ident": {
        "table": "my-table",
        "schema": "{{listSchemas.response.body.$[0].ident.schema}}",
        "database": "{{listDatabases.response.body.$[0].ident}}"
    },
    "format": "iceberg",
    "schema": {
        "schema-id": 0,
        "fields": [
            {
                "id": 0,
                "name": "id",
                "type": "int",
                "required": false
            },
            {
                "id": 1,
                "name": "name",
                "type": "string",
                "required": true
            }
        ]
    }
}

###
# Get a table
# @name getTable

GET {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}/tables/{{listTables.response.body.$[0].ident.table}}

###
# Delete a table
# @name deleteTable

DELETE {{ib_server}}/v1/metastore/databases/{{listDatabases.response.body.$[0].ident}}/schemas/{{listSchemas.response.body.$[0].ident.schema}}/tables/{{listTables.response.body.$[0].ident.table}}

###
# Query all catalogs
# @name df_listCatalogs

POST {{ib_server}}/ui/query
Content-Type: application/json

{
    "query": "SHOW TABLES"
}

###
# Query our table
# @name df_queryTable

POST {{ib_server}}/ui/query
Content-Type: application/json

{
    "query": "SELECT * FROM `{{listDatabases.response.body.$[0].ident}}`.`{{listSchemas.response.body.$[0].ident.schema}}`.`{{listTables.response.body.$[0].ident.table}}`"
}