/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { AuthErrorResponseErrorKind } from './authErrorResponseErrorKind';

export interface AuthErrorResponse {
  errorKind?: AuthErrorResponseErrorKind;
  message: string;
  /** @minimum 0 */
  statusCode: number;
}
