/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type AwsCredentialsOneOfAllOfCredentialType =
  (typeof AwsCredentialsOneOfAllOfCredentialType)[keyof typeof AwsCredentialsOneOfAllOfCredentialType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AwsCredentialsOneOfAllOfCredentialType = {
  access_key: 'access_key',
} as const;
