/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type GetDatabasesParams = {
  /**
   * Databases cursor
   */
  cursor?: string;
  /**
   * Databases limit
   */
  limit?: number;
  /**
   * Databases search (start with)
   */
  search?: string;
};
