/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type GetNavigationTreesParams = {
  /**
   * Navigation trees offset
   */
  offset?: number;
  /**
   * Navigation trees limit
   */
  limit?: number;
};
