/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { I64 } from './i64';

export type GetQueriesParams = {
  /**
   * Worksheet id
   */
  worksheetId?: I64;
  /**
   * Cursor
   */
  cursor?: I64;
  /**
   * Queries limit
   */
  limit?: number;
};
