/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { GetWorksheetsSortBy } from './getWorksheetsSortBy';
import type { GetWorksheetsSortOrder } from './getWorksheetsSortOrder';

export type GetWorksheetsParams = {
  /**
   * Sort order
   */
  sortOrder?: GetWorksheetsSortOrder;
  /**
   * Sort by
   */
  sortBy?: GetWorksheetsSortBy;
};
