/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type GetWorksheetsSortBy = (typeof GetWorksheetsSortBy)[keyof typeof GetWorksheetsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorksheetsSortBy = {
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
