/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type OrderDirection = (typeof OrderDirection)[keyof typeof OrderDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDirection = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
