/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { QueryCreatePayloadContext } from './queryCreatePayloadContext';
import type { QueryCreatePayloadWorksheetId } from './queryCreatePayloadWorksheetId';

export interface QueryCreatePayload {
  context?: QueryCreatePayloadContext;
  query: string;
  worksheetId?: QueryCreatePayloadWorksheetId;
}
