/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { I64 } from './i64';
import type { QueryRecordWorksheetId } from './queryRecordWorksheetId';
import type { QueryStatus } from './queryStatus';
import type { ResultSet } from './resultSet';

export interface QueryRecord {
  durationMs: number;
  endTime: string;
  error: string;
  id: I64;
  query: string;
  result: ResultSet;
  resultCount: number;
  startTime: string;
  status: QueryStatus;
  worksheetId?: QueryRecordWorksheetId;
}
