/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { Column } from './column';
import type { Row } from './row';

export interface ResultSet {
  columns: Column[];
  rows: Row[];
}
