/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { AwsCredentials } from './awsCredentials';
import type { S3TablesVolumeBucket } from './s3TablesVolumeBucket';

export interface S3TablesVolume {
  arn: string;
  bucket?: S3TablesVolumeBucket;
  credentials: AwsCredentials;
  endpoint: string;
  name: string;
  region: string;
}
