/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { S3VolumeBucket } from './s3VolumeBucket';
import type { S3VolumeCredentials } from './s3VolumeCredentials';
import type { S3VolumeEndpoint } from './s3VolumeEndpoint';
import type { S3VolumeMetadataEndpoint } from './s3VolumeMetadataEndpoint';
import type { S3VolumeRegion } from './s3VolumeRegion';
import type { S3VolumeSkipSignature } from './s3VolumeSkipSignature';

export interface S3Volume {
  bucket?: S3VolumeBucket;
  credentials?: S3VolumeCredentials;
  endpoint?: S3VolumeEndpoint;
  metadata_endpoint?: S3VolumeMetadataEndpoint;
  region?: S3VolumeRegion;
  skip_signature?: S3VolumeSkipSignature;
}
