/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { AwsCredentials } from './awsCredentials';

export type S3VolumeCredentials = null | AwsCredentials;
