/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export interface Schema {
  created_at: string;
  database: string;
  name: string;
  updated_at: string;
}
