/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { TablesParametersCursor } from './tablesParametersCursor';
import type { TablesParametersLimit } from './tablesParametersLimit';
import type { TablesParametersSearch } from './tablesParametersSearch';

export interface TablesParameters {
  cursor?: TablesParametersCursor;
  /** @minimum 0 */
  limit?: TablesParametersLimit;
  search?: TablesParametersSearch;
}
