/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export interface Table {
  createdAt: string;
  name: string;
  owner: string;
  totalBytes: number;
  totalRows: number;
  type: string;
  updatedAt: string;
}
