/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type TokenErrorKind = (typeof TokenErrorKind)[keyof typeof TokenErrorKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenErrorKind = {
  invalidToken: 'invalidToken',
  invalidSignature: 'invalidSignature',
  invalidEcdsaKey: 'invalidEcdsaKey',
  invalidRsaKey: 'invalidRsaKey',
  rsaFailedSigning: 'rsaFailedSigning',
  invalidAlgorithmName: 'invalidAlgorithmName',
  invalidKeyFormat: 'invalidKeyFormat',
  missingRequiredClaim: 'missingRequiredClaim',
  expiredSignature: 'expiredSignature',
  invalidIssuer: 'invalidIssuer',
  invalidAudience: 'invalidAudience',
  invalidSubject: 'invalidSubject',
  immatureSignature: 'immatureSignature',
  invalidAlgorithm: 'invalidAlgorithm',
  missingAlgorithm: 'missingAlgorithm',
  other: 'other',
} as const;
