/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type VolumeTypeOneOfFourAllOfType =
  (typeof VolumeTypeOneOfFourAllOfType)[keyof typeof VolumeTypeOneOfFourAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeTypeOneOfFourAllOfType = {
  s3Tables: 's3Tables',
} as const;
