/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type VolumeTypeOneOfOnezeroType =
  (typeof VolumeTypeOneOfOnezeroType)[keyof typeof VolumeTypeOneOfOnezeroType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeTypeOneOfOnezeroType = {
  memory: 'memory',
} as const;
