/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { VolumeTypeOneOf } from './volumeTypeOneOf';
import type { VolumeTypeOneOfFour } from './volumeTypeOneOfFour';
import type { VolumeTypeOneOfOnezero } from './volumeTypeOneOfOnezero';
import type { VolumeTypeOneOfSeven } from './volumeTypeOneOfSeven';

export type VolumeType =
  | VolumeTypeOneOf
  | VolumeTypeOneOfFour
  | VolumeTypeOneOfSeven
  | VolumeTypeOneOfOnezero;
