/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { VolumeTypeOneOfOnezeroType } from './volumeTypeOneOfOnezeroType';

export type VolumeTypeOneOfOnezero = {
  type: VolumeTypeOneOfOnezeroType;
};
