/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type VolumeTypeOneOfAllOfType =
  (typeof VolumeTypeOneOfAllOfType)[keyof typeof VolumeTypeOneOfAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeTypeOneOfAllOfType = {
  s3: 's3',
} as const;
