/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { S3TablesVolume } from './s3TablesVolume';
import type { VolumeTypeOneOfFourAllOf } from './volumeTypeOneOfFourAllOf';

export type VolumeTypeOneOfFour = S3TablesVolume & VolumeTypeOneOfFourAllOf;
