/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { WorksheetUpdatePayloadContent } from './worksheetUpdatePayloadContent';
import type { WorksheetUpdatePayloadName } from './worksheetUpdatePayloadName';

export interface WorksheetUpdatePayload {
  content?: WorksheetUpdatePayloadContent;
  name?: WorksheetUpdatePayloadName;
}
