WITH source AS (
  SELECT *
  FROM {{ source('servicenow_prd','task') }}
),

renamed AS (
  SELECT
    sys_id::VARCHAR                     AS sys_id,
    contact_type::VARCHAR               AS contact_type,
    service_offering_value::VARCHAR     AS service_offering_value,
    group_list::VARCHAR                 AS group_list,
    closed_by_value::VARCHAR            AS closed_by_value,
    work_end::TIMESTAMP                 AS work_end,
    due_date::TIMESTAMP                 AS due_date,
    u_computer_serial_number_value::VARCHAR AS u_computer_serial_number_value,
    work_start::TIMESTAMP               AS work_start,
    correlation_display::VARCHAR        AS correlation_display,
    sys_created_on::TIMESTAMP           AS sys_created_on,
    state::NUMBER                       AS state,
    approval_set::TIMESTAMP             AS approval_set,
    active::BOOLEAN                     AS active,
    sys_created_by::VARCHAR             AS sys_created_by,
    task_effective_number::VARCHAR      AS task_effective_number,
    sys_class_name::VARCHAR             AS sys_class_name,
    parent_value::VARCHAR               AS parent_value,
    activity_due::TIMESTAMP             AS activity_due,
    expected_start::TIMESTAMP           AS expected_start,
    opened_at::TIMESTAMP                AS opened_at,
    universal_request_value::VARCHAR    AS universal_request_value,
    sys_mod_count::NUMBER               AS sys_mod_count,
    opened_by_value::VARCHAR            AS opened_by_value,
    upon_approval::VARCHAR              AS upon_approval,
    made_sla::BOOLEAN                   AS made_sla,
    priority::NUMBER                    AS priority,
    closed_at::TIMESTAMP                AS closed_at,
    sla_due::TIMESTAMP                  AS sla_due,
    business_duration::TIMESTAMP        AS business_duration,
    correlation_id::VARCHAR             AS correlation_id,
    sys_updated_on::TIMESTAMP           AS sys_updated_on,
    assigned_to_value::VARCHAR          AS assigned_to_value,
    urgency::NUMBER                     AS urgency,
    reassignment_count::NUMBER          AS reassignment_count,
    contract_value::VARCHAR             AS contract_value,
    assignment_group_value::VARCHAR     AS assignment_group_value,
    number::VARCHAR                     AS number,
    business_service_value::VARCHAR     AS business_service_value,
    sys_domain_path::VARCHAR            AS sys_domain_path,
    cmdb_ci_value::VARCHAR              AS cmdb_ci_value,
    calendar_duration::TIMESTAMP        AS calendar_duration,
    sys_updated_by::VARCHAR             AS sys_updated_by,
    approval_history::VARCHAR           AS approval_history,
    follow_up::TIMESTAMP                AS follow_up,
    additional_assignee_list::VARCHAR   AS additional_assignee_list,
    rejection_goto_value::VARCHAR       AS rejection_goto_value,
    approval::VARCHAR                   AS approval,
    _fivetran_synced::TIMESTAMP         AS _fivetran_synced,
    _fivetran_deleted::BOOLEAN          AS _fivetran_deleted
  FROM source
)

SELECT * FROM renamed