{{ config(
    tags=["mnpi", "six_hourly"]
) }}

WITH source AS (

  SELECT *
  FROM {{ ref('sfdc_opportunity_snapshots') }}
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
      dbt_valid_from::DATE,
      id
    ORDER BY dbt_valid_from DESC
  ) = 1

),

renamed AS (
  SELECT
    -- keys
    accountid::VARCHAR                                        AS account_id,
    id::VARCHAR                                               AS opportunity_id,
    name::VARCHAR                                             AS opportunity_name,
    ownerid::VARCHAR                                          AS owner_id,

    -- logistical information
    isclosed::BOOLEAN                                         AS is_closed,
    iswon::BOOLEAN                                            AS is_won,
    valid_deal_count__c::FLOAT                                AS valid_deal_count,
    closedate::TIMESTAMP_NTZ                                  AS close_date,
    createddate::TIMESTAMP_NTZ                                AS created_date,
    deployment_preference__c::VARCHAR                         AS deployment_preference,
    sql_source__c::VARCHAR                                    AS generated_source,
    leadsource::VARCHAR                                       AS lead_source,
    merged_opportunity__c::VARCHAR                            AS merged_opportunity_id,
    duplicate_opportunity__c::VARCHAR                         AS duplicate_opportunity_id,
    contract_reset_opportunity__c::VARCHAR                    AS contract_reset_opportunity_id,
    account_owner__c::VARCHAR                                 AS account_owner,
    opportunity_owner__c::VARCHAR                             AS opportunity_owner,
    manager_current__c::VARCHAR                               AS opportunity_owner_manager,
    sales_market__c::VARCHAR                                  AS opportunity_owner_department,
    sdr_lu__c::VARCHAR                                        AS crm_sales_dev_rep_id,
    business_development_representative__c::VARCHAR           AS crm_business_dev_rep_id,
    bdr_lu__c::VARCHAR                                        AS crm_business_dev_rep_id_lookup,
    bdr_sdr__c::VARCHAR                                       AS opportunity_development_representative,
    sales_accepted_date__c::TIMESTAMP_NTZ                     AS sales_accepted_date,
    engagement_type__c::VARCHAR                               AS sales_path,
    sales_qualified_date__c::TIMESTAMP_NTZ                    AS sales_qualified_date,
    iqm_submitted_by_role__c::VARCHAR                         AS iqm_submitted_by_role,
    type::VARCHAR                                             AS subscription_type,
    stagename::VARCHAR                                        AS stage_name,

    -- opportunity information
    acv_2__c::FLOAT                                           AS acv,
    amount::FLOAT                                             AS amount,
    competitors__c::VARCHAR                                   AS competitors,
    critical_deal_flag__c::VARCHAR                            AS critical_deal_flag,
    forecastcategoryname::VARCHAR                             AS forecast_category_name,
    incremental_acv_2__c::FLOAT                               AS forecasted_iacv,
    iacv_created_date__c::TIMESTAMP_NTZ                       AS iacv_created_date,
    incremental_acv__c::FLOAT                                 AS incremental_acv,
    invoice_number__c::VARCHAR                                AS invoice_number,
    is_refund_opportunity__c::FLOAT                           AS is_refund,
    is_downgrade_opportunity__c::FLOAT                        AS is_downgrade,
    swing_deal__c::BOOLEAN                                    AS is_swing_deal,
    is_edu_oss_opportunity__c::FLOAT                          AS is_edu_oss,
    is_ps_opportunity__c::FLOAT                               AS is_ps_opp,
    net_iacv__c::FLOAT                                        AS net_incremental_acv,
    campaignid::VARCHAR                                       AS primary_campaign_source_id,
    probability::FLOAT                                        AS probability,
    professional_services_value__c::FLOAT                     AS professional_services_value,
    edu_services_value__c::FLOAT                              AS edu_services_value,
    investment_services_value__c::FLOAT                       AS investment_services_value,
    push_counter__c::FLOAT                                    AS pushed_count,
    reason_for_lost__c::VARCHAR                               AS reason_for_loss,
    reason_for_lost_details__c::VARCHAR                       AS reason_for_loss_details,
    refund_iacv__c::FLOAT                                     AS refund_iacv,
    downgrade_iacv__c::FLOAT                                  AS downgrade_iacv,
    renewal_acv__c::FLOAT                                     AS renewal_acv,
    renewal_amount__c::FLOAT                                  AS renewal_amount,
    sdr_pipeline_contribution__c::FLOAT                       AS sdr_pipeline_contribution,
    solutions_to_be_replaced__c::VARCHAR                      AS solutions_to_be_replaced,
    x3_technical_evaluation_date__c::TIMESTAMP_NTZ            AS technical_evaluation_date,
    amount::FLOAT                                             AS total_contract_value,
    recurring_amount__c::FLOAT                                AS recurring_amount,
    true_up_amount__c::FLOAT                                  AS true_up_amount,
    proserv_amount__c::FLOAT                                  AS proserv_amount,
    other_non_recurring_amount__c::FLOAT                      AS other_non_recurring_amount,
    upside_swing_deal_iacv__c::FLOAT                          AS upside_swing_deal_iacv,
    web_portal_purchase__c::BOOLEAN                           AS is_web_portal_purchase,
    opportunity_term_new__c::FLOAT                            AS opportunity_term,
    pio__c::BOOLEAN                                           AS partner_initiated_opportunity,
    user_segment_o__c::VARCHAR                                AS user_segment,
    start_date__c::DATE                                       AS subscription_start_date,
    end_date__c::DATE                                         AS subscription_end_date,
    subscription_renewal_date__c::DATE                        AS subscription_renewal_date,
    true_up_value__c::FLOAT                                   AS true_up_value,
    order_type_live__c::VARCHAR                               AS order_type_current,
    order_type_test__c::VARCHAR                               AS order_type_stamped,
    arr_net__c::FLOAT                                         AS net_arr,
    arr_basis__c::FLOAT                                       AS arr_basis,
    arr__c::FLOAT                                             AS arr,
    stage_3_net_arr__c::FLOAT                                 AS xdr_net_arr_stage_3,
    stage_1_xdr_net_arr__c::FLOAT                             AS xdr_net_arr_stage_1,
    stage_1_net_arr__c::FLOAT                                 AS net_arr_stage_1,
    enterprise_agile_planning_net_arr__c::FLOAT               AS enterprise_agile_planning_net_arr,
    duo_net_arr__c::FLOAT                                     AS duo_net_arr,
    days_in_sao__c::FLOAT                                     AS days_in_sao,
    new_logo_count__c::FLOAT                                  AS new_logo_count,
    stamped_user_geo__c::VARCHAR                              AS user_geo_stamped,
    stamped_user_region__c::VARCHAR                           AS user_region_stamped,
    stamped_user_area__c::VARCHAR                             AS user_area_stamped,
    stamped_opp_owner_user_role_type__c::VARCHAR              AS crm_opp_owner_user_role_type_stamped,
    stamped_opp_owner_user_business_unit__c::VARCHAR          AS user_business_unit_stamped,
    stamped_opportunity_owner__c::VARCHAR                     AS crm_opp_owner_stamped_name,
    stamped_account_owner__c::VARCHAR                         AS crm_account_owner_stamped_name,
    sao_user_segment__c::VARCHAR                              AS sao_crm_opp_owner_sales_segment_stamped,
    sao_opp_owner_segment_geo_region_area__c::VARCHAR         AS sao_crm_opp_owner_sales_segment_geo_region_area_stamped,
    sao_user_geo__c::VARCHAR                                  AS sao_crm_opp_owner_geo_stamped,
    sao_user_region__c::VARCHAR                               AS sao_crm_opp_owner_region_stamped,
    sao_user_area__c::VARCHAR                                 AS sao_crm_opp_owner_area_stamped,
    opportunity_category__c::VARCHAR                          AS opportunity_category,
    opportunity_health__c::VARCHAR                            AS opportunity_health,
    number_of_sa_activity_tasks__c::VARCHAR                   AS number_of_sa_activity_tasks,
    risk_type__c::VARCHAR                                     AS risk_type,
    risk_reasons__c::VARCHAR                                  AS risk_reasons,
    tam_notes__c::VARCHAR                                     AS tam_notes,
    solution_architect__c::VARCHAR                            AS primary_solution_architect,
    product_details__c::VARCHAR                               AS product_details,
    product_category__c::VARCHAR                              AS product_category,
    products_purchased__c::VARCHAR                            AS products_purchased,
    payment_schedule__c::VARCHAR                              AS payment_schedule,
    comp_new_logo_override__c::VARCHAR                        AS comp_new_logo_override,
    is_pipeline_created_eligible_flag__c::BOOLEAN             AS is_pipeline_created_eligible,
    next_steps__c::VARCHAR                                    AS next_steps,
    auto_renewal_status__c::VARCHAR                           AS auto_renewal_status,
    qsr_notes__c::VARCHAR                                     AS qsr_notes,
    qsr_status__c::VARCHAR                                    AS qsr_status,
    manager_forecast_confidence__c::FLOAT                     AS manager_confidence,
    renewal_risk_forecast__c::VARCHAR                         AS renewal_risk_category,
    renewal_swing_arr__c::FLOAT                               AS renewal_swing_arr,
    isr__c::VARCHAR                                           AS renewal_manager,
    renewal_forecast_category__c::VARCHAR                     AS renewal_forecast_health,
    startup_type__c::VARCHAR                                  AS startup_type,
    sales_segmentation_employees_o__c::VARCHAR                AS sales_segmentation_employees,
    ultimate_parent_sales_segment_emp_o__c::VARCHAR           AS ultimate_parent_sales_segment_emp,
    deal_path__c::VARCHAR                                     AS deal_path,

    -- dates in stage fields
    days_in_0_pending_acceptance__c::FLOAT                    AS days_in_0_pending_acceptance,
    days_in_1_discovery__c::FLOAT                             AS days_in_1_discovery,
    days_in_2_scoping__c::FLOAT                               AS days_in_2_scoping,
    days_in_3_technical_evaluation__c::FLOAT                  AS days_in_3_technical_evaluation,
    days_in_4_proposal__c::FLOAT                              AS days_in_4_proposal,
    days_in_5_negotiating__c::FLOAT                           AS days_in_5_negotiating,
    x0_pending_acceptance_date__c::TIMESTAMP_NTZ              AS stage_0_pending_acceptance_date,
    x1_discovery_date__c::TIMESTAMP_NTZ                       AS stage_1_discovery_date,
    x2_scoping_date__c::TIMESTAMP_NTZ                         AS stage_2_scoping_date,
    x3_technical_evaluation_date__c::TIMESTAMP_NTZ            AS stage_3_technical_evaluation_date,
    x4_proposal_date__c::TIMESTAMP_NTZ                        AS stage_4_proposal_date,
    x5_negotiating_date__c::TIMESTAMP_NTZ                     AS stage_5_negotiating_date,
    x6_awaiting_signature_date__c::TIMESTAMP_NTZ              AS stage_6_awaiting_signature_date,
    x6_closed_won_date__c::TIMESTAMP_NTZ                      AS stage_6_closed_won_date,
    x7_closed_lost_date__c::TIMESTAMP_NTZ                     AS stage_6_closed_lost_date,

    -- channel reporting
    -- original issue: https://gitlab.com/gitlab-data/analytics/-/issues/6072
    dr_partner_deal_type__c::VARCHAR                          AS dr_partner_deal_type,
    dr_partner_engagement__c::VARCHAR                         AS dr_partner_engagement,
    vartopiadrs__dr_deal_reg_id__c::VARCHAR                   AS dr_deal_id,
    vartopiadrs__primary_registration__c::VARCHAR             AS dr_primary_registration,
    impartnerprm__partneraccount__c::VARCHAR                  AS partner_account,
    vartopiadrs__dr_status1__c::VARCHAR                       AS dr_status,
    distributor__c::VARCHAR                                   AS distributor,
    influence_partner__c::VARCHAR                             AS influence_partner,
    focus_partner__c::BOOLEAN                                 AS is_focus_partner,
    fulfillment_partner__c::VARCHAR                           AS fulfillment_partner,
    platform_partner__c::VARCHAR                              AS platform_partner,
    partner_track__c::VARCHAR                                 AS partner_track,
    resale_partner_track__c::VARCHAR                          AS resale_partner_track,
    public_sector_opp__c::BOOLEAN                             AS is_public_sector_opp,
    registration_from_portal__c::BOOLEAN                      AS is_registration_from_portal,
    calculated_discount__c::FLOAT                             AS calculated_discount,
    partner_discount__c::FLOAT                                AS partner_discount,
    partner_discount_calc__c::FLOAT                           AS partner_discount_calc,
    partner_margin__c::FLOAT                                  AS partner_margin_percentage,
    comp_channel_neutral__c::FLOAT                            AS comp_channel_neutral,
    aggregate_partner__c::VARCHAR                             AS aggregate_partner,

    -- command plan fields
    fm_champion__c::VARCHAR                                   AS cp_champion,
    fm_close_plan__c::VARCHAR                                 AS cp_close_plan,
    fm_decision_criteria__c::VARCHAR                          AS cp_decision_criteria,
    fm_decision_process__c::VARCHAR                           AS cp_decision_process,
    fm_economic_buyer__c::VARCHAR                             AS cp_economic_buyer,
    fm_help__c::VARCHAR                                       AS cp_help,
    fm_identify_pain__c::VARCHAR                              AS cp_identify_pain,
    fm_metrics__c::VARCHAR                                    AS cp_metrics,
    fm_partner__c::VARCHAR                                    AS cp_partner,
    fm_paper_process__c::VARCHAR                              AS cp_paper_process,
    fm_review_notes__c::VARCHAR                               AS cp_review_notes,
    fm_risks__c::VARCHAR                                      AS cp_risks,
    fm_use_cases__c::VARCHAR                                  AS cp_use_cases,
    fm_value_driver__c::VARCHAR                               AS cp_value_driver,
    fm_why_do_anything_at_all__c::VARCHAR                     AS cp_why_do_anything_at_all,
    fm_why_gitlab__c::VARCHAR                                 AS cp_why_gitlab,
    fm_why_now__c::VARCHAR                                    AS cp_why_now,
    fm_score__c::FLOAT                                        AS cp_score,

    -- original issue: https://gitlab.com/gitlab-data/analytics/-/issues/6577
    sa_validated_tech_evaluation_close_statu__c::VARCHAR      AS sa_tech_evaluation_close_status,
    sa_validated_tech_evaluation_end_date__c::TIMESTAMP_NTZ   AS sa_tech_evaluation_end_date,
    sa_validated_tech_evaluation_start_date__c::TIMESTAMP_NTZ AS sa_tech_evaluation_start_date,

    -- flag to identify eligible booking deals, excluding jihu - issue: https://gitlab.com/gitlab-com/sales-team/field-operations/systems/-/issues/1805
    fp_a_master_bookings_flag__c::BOOLEAN                     AS fpa_master_bookings_flag,
    downgrade_reason__c::VARCHAR                              AS downgrade_reason,
    ssp_id__c::VARCHAR                                        AS ssp_id,
    gaclientid__c::VARCHAR                                    AS ga_client_id,

    -- vsa data - issue: https://gitlab.com/gitlab-com/sales-team/field-operations/customer-success-operations/-/issues/2399
    vsa_readout__c::VARCHAR                                   AS vsa_readout,
    vsa_start_date_net_arr__c::FLOAT                          AS vsa_start_date_net_arr,
    vsa_start_date__c::TIMESTAMP_NTZ                          AS vsa_start_date,
    vsa_url__c::VARCHAR                                       AS vsa_url,
    vsa_status__c::VARCHAR                                    AS vsa_status,
    vsa_end_date__c::TIMESTAMP_NTZ                            AS vsa_end_date,

    -- original issue: https://gitlab.com/gitlab-com/sales-team/field-operations/customer-success-operations/-/issues/2464
    downgrade_details__c::VARCHAR                             AS downgrade_details,
    won_arr_basis_for_clari__c::FLOAT                         AS won_arr_basis_for_clari,
    arr_basis_for_clari__c::FLOAT                             AS arr_basis_for_clari,
    forecasted_churn_for_clari__c::FLOAT                      AS forecasted_churn_for_clari,
    override_arr_basis_clari__c::FLOAT                        AS override_arr_basis_clari,

    -- ps fields - issue: https://gitlab.com/gitlab-com/sales-team/field-operations/customer-success-operations/-/issues/2723
    intended_product_tier__c::VARCHAR                         AS intended_product_tier,
    parent_opportunity__c::VARCHAR                            AS parent_opportunity_id,

    -- ptc fields - issue: https://gitlab.com/gitlab-data/analytics/-/issues/19440
    ptc_predicted_arr__c::FLOAT                               AS ptc_predicted_arr,
    ptc_predicted_renewal_risk_category__c::VARCHAR           AS ptc_predicted_renewal_risk_category,

    -- metadata
    isdeleted::BOOLEAN                                        AS is_deleted,
    lastactivitydate::TIMESTAMP_NTZ                           AS last_activity_date,
    sales_last_activity_date__c::TIMESTAMP_NTZ                AS sales_last_activity_date,
    recordtypeid::VARCHAR                                     AS record_type_id,
    dbt_scd_id::VARCHAR                                       AS dbt_scd_id,
    dbt_updated_at::TIMESTAMP_NTZ                             AS dbt_updated_at,
    dbt_valid_from::TIMESTAMP_NTZ                             AS dbt_valid_from,
    dbt_valid_to::TIMESTAMP_NTZ                               AS dbt_valid_to,
    _sdc_received_at::TIMESTAMP_NTZ                           AS sdc_received_at,
    _sdc_sequence::NUMBER                                     AS sdc_sequence,
    _sdc_batched_at::TIMESTAMP_NTZ                            AS sdc_batched_at,
    _sdc_extracted_at::TIMESTAMP_NTZ                          AS sdc_extracted_at
  FROM source
)

SELECT *
FROM renamed
