/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useAxiosMutator } from '../lib/axiosMutator';
import type { ErrorType } from '../lib/axiosMutator';
import type {
  ErrorResponse,
  GetVolumesParams,
  VolumeCreatePayload,
  VolumeCreateResponse,
  VolumeResponse,
  VolumesResponse,
} from './models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getVolumes = (
  params?: GetVolumesParams,
  options?: SecondParameter<typeof useAxiosMutator>,
  signal?: AbortSignal,
) => {
  return useAxiosMutator<VolumesResponse>(
    { url: `/ui/volumes`, method: 'GET', params, signal },
    options,
  );
};

export const getGetVolumesQueryKey = (params?: GetVolumesParams) => {
  return [`/ui/volumes`, ...(params ? [params] : [])] as const;
};

export const getGetVolumesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVolumes>>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVolumesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVolumes>>> = ({ signal }) =>
    getVolumes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVolumes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVolumesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVolumes>>>;
export type GetVolumesInfiniteQueryError = ErrorType<ErrorResponse>;

export function useGetVolumesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolumes>>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | GetVolumesParams,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolumes>>,
          TError,
          Awaited<ReturnType<typeof getVolumes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolumes>>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolumes>>,
          TError,
          Awaited<ReturnType<typeof getVolumes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolumes>>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVolumesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolumes>>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVolumesInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetVolumesQueryOptions = <
  TData = Awaited<ReturnType<typeof getVolumes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVolumesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVolumes>>> = ({ signal }) =>
    getVolumes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVolumes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVolumesQueryResult = NonNullable<Awaited<ReturnType<typeof getVolumes>>>;
export type GetVolumesQueryError = ErrorType<ErrorResponse>;

export function useGetVolumes<
  TData = Awaited<ReturnType<typeof getVolumes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | GetVolumesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolumes>>,
          TError,
          Awaited<ReturnType<typeof getVolumes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumes<
  TData = Awaited<ReturnType<typeof getVolumes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolumes>>,
          TError,
          Awaited<ReturnType<typeof getVolumes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumes<
  TData = Awaited<ReturnType<typeof getVolumes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVolumes<
  TData = Awaited<ReturnType<typeof getVolumes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetVolumesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolumes>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVolumesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createVolume = (
  volumeCreatePayload: VolumeCreatePayload,
  options?: SecondParameter<typeof useAxiosMutator>,
  signal?: AbortSignal,
) => {
  return useAxiosMutator<VolumeCreateResponse>(
    {
      url: `/ui/volumes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: volumeCreatePayload,
      signal,
    },
    options,
  );
};

export const getCreateVolumeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVolume>>,
    TError,
    { data: VolumeCreatePayload },
    TContext
  >;
  request?: SecondParameter<typeof useAxiosMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVolume>>,
  TError,
  { data: VolumeCreatePayload },
  TContext
> => {
  const mutationKey = ['createVolume'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVolume>>,
    { data: VolumeCreatePayload }
  > = (props) => {
    const { data } = props ?? {};

    return createVolume(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateVolumeMutationResult = NonNullable<Awaited<ReturnType<typeof createVolume>>>;
export type CreateVolumeMutationBody = VolumeCreatePayload;
export type CreateVolumeMutationError = ErrorType<ErrorResponse>;

export const useCreateVolume = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createVolume>>,
      TError,
      { data: VolumeCreatePayload },
      TContext
    >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createVolume>>,
  TError,
  { data: VolumeCreatePayload },
  TContext
> => {
  const mutationOptions = getCreateVolumeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getVolume = (
  volumeName: string,
  options?: SecondParameter<typeof useAxiosMutator>,
  signal?: AbortSignal,
) => {
  return useAxiosMutator<VolumeResponse>(
    { url: `/ui/volumes/${volumeName}`, method: 'GET', signal },
    options,
  );
};

export const getGetVolumeQueryKey = (volumeName: string) => {
  return [`/ui/volumes/${volumeName}`] as const;
};

export const getGetVolumeInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVolume>>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVolumeQueryKey(volumeName);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVolume>>> = ({ signal }) =>
    getVolume(volumeName, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!volumeName, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVolume>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVolumeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVolume>>>;
export type GetVolumeInfiniteQueryError = ErrorType<ErrorResponse>;

export function useGetVolumeInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolume>>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolume>>,
          TError,
          Awaited<ReturnType<typeof getVolume>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumeInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolume>>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolume>>,
          TError,
          Awaited<ReturnType<typeof getVolume>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolumeInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolume>>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVolumeInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVolume>>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVolumeInfiniteQueryOptions(volumeName, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetVolumeQueryOptions = <
  TData = Awaited<ReturnType<typeof getVolume>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVolumeQueryKey(volumeName);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVolume>>> = ({ signal }) =>
    getVolume(volumeName, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!volumeName, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVolume>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVolumeQueryResult = NonNullable<Awaited<ReturnType<typeof getVolume>>>;
export type GetVolumeQueryError = ErrorType<ErrorResponse>;

export function useGetVolume<
  TData = Awaited<ReturnType<typeof getVolume>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolume>>,
          TError,
          Awaited<ReturnType<typeof getVolume>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolume<
  TData = Awaited<ReturnType<typeof getVolume>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVolume>>,
          TError,
          Awaited<ReturnType<typeof getVolume>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVolume<
  TData = Awaited<ReturnType<typeof getVolume>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVolume<
  TData = Awaited<ReturnType<typeof getVolume>>,
  TError = ErrorType<ErrorResponse>,
>(
  volumeName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVolume>>, TError, TData>>;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVolumeQueryOptions(volumeName, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteVolume = (
  volumeName: string,
  options?: SecondParameter<typeof useAxiosMutator>,
) => {
  return useAxiosMutator<void>({ url: `/ui/volumes/${volumeName}`, method: 'DELETE' }, options);
};

export const getDeleteVolumeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVolume>>,
    TError,
    { volumeName: string },
    TContext
  >;
  request?: SecondParameter<typeof useAxiosMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVolume>>,
  TError,
  { volumeName: string },
  TContext
> => {
  const mutationKey = ['deleteVolume'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVolume>>,
    { volumeName: string }
  > = (props) => {
    const { volumeName } = props ?? {};

    return deleteVolume(volumeName, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVolumeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVolume>>>;

export type DeleteVolumeMutationError = ErrorType<ErrorResponse>;

export const useDeleteVolume = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVolume>>,
      TError,
      { volumeName: string },
      TContext
    >;
    request?: SecondParameter<typeof useAxiosMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVolume>>,
  TError,
  { volumeName: string },
  TContext
> => {
  const mutationOptions = getDeleteVolumeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
